// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj_V7cCMBEYvFVvHlD_-KZ0HEonwhXeUM',
    appId: '1:1060198123769:web:bf59b51757c3f460c13a28',
    messagingSenderId: '1060198123769',
    projectId: 'music-app-9ee48',
    authDomain: 'music-app-9ee48.firebaseapp.com',
    storageBucket: 'music-app-9ee48.appspot.com',
    measurementId: 'G-3VPBJ6XJ0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7IXuap7p0Do_oFtPbyrn7wSYsubZmMTQ',
    appId: '1:1060198123769:android:d1d3e329c5a02442c13a28',
    messagingSenderId: '1060198123769',
    projectId: 'music-app-9ee48',
    storageBucket: 'music-app-9ee48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADbzBFqDEPLmadnf1mTlhSciYxw0v7cKs',
    appId: '1:1060198123769:ios:bc571549c4f5e36cc13a28',
    messagingSenderId: '1060198123769',
    projectId: 'music-app-9ee48',
    storageBucket: 'music-app-9ee48.appspot.com',
    iosBundleId: 'com.example.bmpMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADbzBFqDEPLmadnf1mTlhSciYxw0v7cKs',
    appId: '1:1060198123769:ios:bc571549c4f5e36cc13a28',
    messagingSenderId: '1060198123769',
    projectId: 'music-app-9ee48',
    storageBucket: 'music-app-9ee48.appspot.com',
    iosBundleId: 'com.example.bmpMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj_V7cCMBEYvFVvHlD_-KZ0HEonwhXeUM',
    appId: '1:1060198123769:web:03a7ba0600d5077dc13a28',
    messagingSenderId: '1060198123769',
    projectId: 'music-app-9ee48',
    authDomain: 'music-app-9ee48.firebaseapp.com',
    storageBucket: 'music-app-9ee48.appspot.com',
    measurementId: 'G-2HNS3X6N5Y',
  );
}
